version: '3.8'

services:
  app:
    image: "ewr.vultrcr.com/olivertechnologysolutions/bright-haven-cleaning:0.9"
    container_name: flask_app
    expose:
      - "5000"
    networks:
      - web

  caddy:
    image: caddy:latest
    container_name: caddy_reverse_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
    networks:
      - web

volumes:
  caddy_data:
  caddy_config:

networks:
  web:

